// AUTO-GENERATED by scripts/gen-db-types.ts — do not edit by hand. Run `npm run db:types`.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      activity_logs: {
        Row: {
          id: string;
          type: string;
          description: string;
          actor_id: string | null;
          client_id: string | null;
          project_id: string | null;
          entity_type: string | null;
          entity_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          type: string;
          description: string;
          actor_id?: string | null;
          client_id?: string | null;
          project_id?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          description?: string;
          actor_id?: string | null;
          client_id?: string | null;
          project_id?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "activity_logs_actor_id_fkey"; columns: ["actor_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "activity_logs_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "activity_logs_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
        ];
      };
      approval_feedback: {
        Row: {
          id: string;
          approval_id: string;
          decision: string;
          comment: string | null;
          author_name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          approval_id: string;
          decision: string;
          comment?: string | null;
          author_name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          approval_id?: string;
          decision?: string;
          comment?: string | null;
          author_name?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "approval_feedback_approval_id_fkey"; columns: ["approval_id"]; isOneToOne: false; referencedRelation: "project_approvals"; referencedColumns: ["id"] },
        ];
      };
      clients: {
        Row: {
          id: string;
          name: string;
          business_name: string | null;
          phone: string | null;
          phone_digits: string | null;
          email: string | null;
          website: string | null;
          status: Database["public"]["Enums"]["client_status"];
          source: Database["public"]["Enums"]["lead_source"] | null;
          notes: string | null;
          archived_at: string | null;
          is_demo: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          business_name?: string | null;
          phone?: string | null;
          phone_digits?: never;
          email?: string | null;
          website?: string | null;
          status?: Database["public"]["Enums"]["client_status"];
          source?: Database["public"]["Enums"]["lead_source"] | null;
          notes?: string | null;
          archived_at?: string | null;
          is_demo?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          business_name?: string | null;
          phone?: string | null;
          phone_digits?: never;
          email?: string | null;
          website?: string | null;
          status?: Database["public"]["Enums"]["client_status"];
          source?: Database["public"]["Enums"]["lead_source"] | null;
          notes?: string | null;
          archived_at?: string | null;
          is_demo?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "clients_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      contracts: {
        Row: {
          id: string;
          client_id: string;
          project_id: string | null;
          title: string;
          status: Database["public"]["Enums"]["contract_status"];
          contract_date: string | null;
          signed_at: string | null;
          file_id: string | null;
          notes: string | null;
          template_id: string | null;
          signature_provider: string | null;
          signature_request_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          contract_number: string | null;
          content: Json | null;
        };
        Insert: {
          id?: string;
          client_id: string;
          project_id?: string | null;
          title: string;
          status?: Database["public"]["Enums"]["contract_status"];
          contract_date?: string | null;
          signed_at?: string | null;
          file_id?: string | null;
          notes?: string | null;
          template_id?: string | null;
          signature_provider?: string | null;
          signature_request_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          contract_number?: string | null;
          content?: Json | null;
        };
        Update: {
          id?: string;
          client_id?: string;
          project_id?: string | null;
          title?: string;
          status?: Database["public"]["Enums"]["contract_status"];
          contract_date?: string | null;
          signed_at?: string | null;
          file_id?: string | null;
          notes?: string | null;
          template_id?: string | null;
          signature_provider?: string | null;
          signature_request_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          contract_number?: string | null;
          content?: Json | null;
        };
        Relationships: [
          { foreignKeyName: "contracts_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "contracts_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "contracts_file_id_fkey"; columns: ["file_id"]; isOneToOne: false; referencedRelation: "files"; referencedColumns: ["id"] },
          { foreignKeyName: "contracts_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
        ];
      };
      files: {
        Row: {
          id: string;
          bucket: string;
          storage_path: string;
          original_name: string;
          mime_type: string;
          size_bytes: number;
          category: Database["public"]["Enums"]["file_category"];
          client_id: string | null;
          project_id: string | null;
          submission_id: string | null;
          question_id: string | null;
          uploaded_by: string | null;
          source: string;
          created_at: string;
          updated_at: string;
          album_id: string | null;
          album_section: string | null;
          task_id: string | null;
          is_shared: boolean;
        };
        Insert: {
          id?: string;
          bucket?: string;
          storage_path: string;
          original_name: string;
          mime_type: string;
          size_bytes: number;
          category?: Database["public"]["Enums"]["file_category"];
          client_id?: string | null;
          project_id?: string | null;
          submission_id?: string | null;
          question_id?: string | null;
          uploaded_by?: string | null;
          source?: string;
          created_at?: string;
          updated_at?: string;
          album_id?: string | null;
          album_section?: string | null;
          task_id?: string | null;
          is_shared?: boolean;
        };
        Update: {
          id?: string;
          bucket?: string;
          storage_path?: string;
          original_name?: string;
          mime_type?: string;
          size_bytes?: number;
          category?: Database["public"]["Enums"]["file_category"];
          client_id?: string | null;
          project_id?: string | null;
          submission_id?: string | null;
          question_id?: string | null;
          uploaded_by?: string | null;
          source?: string;
          created_at?: string;
          updated_at?: string;
          album_id?: string | null;
          album_section?: string | null;
          task_id?: string | null;
          is_shared?: boolean;
        };
        Relationships: [
          { foreignKeyName: "files_album_id_fkey"; columns: ["album_id"]; isOneToOne: false; referencedRelation: "social_albums"; referencedColumns: ["id"] },
          { foreignKeyName: "files_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "files_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
          { foreignKeyName: "files_submission_id_fkey"; columns: ["submission_id"]; isOneToOne: false; referencedRelation: "form_submissions"; referencedColumns: ["id"] },
          { foreignKeyName: "files_task_id_fkey"; columns: ["task_id"]; isOneToOne: false; referencedRelation: "tasks"; referencedColumns: ["id"] },
          { foreignKeyName: "files_uploaded_by_fkey"; columns: ["uploaded_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      form_answers: {
        Row: {
          id: string;
          submission_id: string;
          question_id: string;
          section_title: string;
          section_position: number;
          question_label: string;
          question_type: Database["public"]["Enums"]["question_type"];
          position: number;
          value: Json | null;
          internal_note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          submission_id: string;
          question_id: string;
          section_title?: string;
          section_position?: number;
          question_label: string;
          question_type: Database["public"]["Enums"]["question_type"];
          position?: number;
          value?: Json | null;
          internal_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          submission_id?: string;
          question_id?: string;
          section_title?: string;
          section_position?: number;
          question_label?: string;
          question_type?: Database["public"]["Enums"]["question_type"];
          position?: number;
          value?: Json | null;
          internal_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "form_answers_submission_id_fkey"; columns: ["submission_id"]; isOneToOne: false; referencedRelation: "form_submissions"; referencedColumns: ["id"] },
        ];
      };
      form_questions: {
        Row: {
          id: string;
          section_id: string;
          type: Database["public"]["Enums"]["question_type"];
          label: string;
          description: string | null;
          placeholder: string | null;
          required: boolean;
          options: Json;
          condition: Json | null;
          maps_to: string | null;
          position: number;
          created_at: string;
          updated_at: string;
          max_choices: number | null;
        };
        Insert: {
          id?: string;
          section_id: string;
          type?: Database["public"]["Enums"]["question_type"];
          label?: string;
          description?: string | null;
          placeholder?: string | null;
          required?: boolean;
          options?: Json;
          condition?: Json | null;
          maps_to?: string | null;
          position?: number;
          created_at?: string;
          updated_at?: string;
          max_choices?: number | null;
        };
        Update: {
          id?: string;
          section_id?: string;
          type?: Database["public"]["Enums"]["question_type"];
          label?: string;
          description?: string | null;
          placeholder?: string | null;
          required?: boolean;
          options?: Json;
          condition?: Json | null;
          maps_to?: string | null;
          position?: number;
          created_at?: string;
          updated_at?: string;
          max_choices?: number | null;
        };
        Relationships: [
          { foreignKeyName: "form_questions_section_id_fkey"; columns: ["section_id"]; isOneToOne: false; referencedRelation: "form_sections"; referencedColumns: ["id"] },
        ];
      };
      form_sections: {
        Row: {
          id: string;
          template_id: string;
          title: string;
          description: string | null;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          template_id: string;
          title?: string;
          description?: string | null;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          template_id?: string;
          title?: string;
          description?: string | null;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "form_sections_template_id_fkey"; columns: ["template_id"]; isOneToOne: false; referencedRelation: "form_templates"; referencedColumns: ["id"] },
        ];
      };
      form_submissions: {
        Row: {
          id: string;
          token: string;
          template_id: string | null;
          client_id: string | null;
          project_id: string | null;
          title: string;
          form_snapshot: Json;
          status: Database["public"]["Enums"]["submission_status"];
          draft_answers: Json;
          draft_step: number;
          internal_notes: string | null;
          sent_at: string | null;
          opened_at: string | null;
          started_at: string | null;
          last_saved_at: string | null;
          completed_at: string | null;
          expires_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          token: string;
          template_id?: string | null;
          client_id?: string | null;
          project_id?: string | null;
          title: string;
          form_snapshot: Json;
          status?: Database["public"]["Enums"]["submission_status"];
          draft_answers?: Json;
          draft_step?: number;
          internal_notes?: string | null;
          sent_at?: string | null;
          opened_at?: string | null;
          started_at?: string | null;
          last_saved_at?: string | null;
          completed_at?: string | null;
          expires_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          token?: string;
          template_id?: string | null;
          client_id?: string | null;
          project_id?: string | null;
          title?: string;
          form_snapshot?: Json;
          status?: Database["public"]["Enums"]["submission_status"];
          draft_answers?: Json;
          draft_step?: number;
          internal_notes?: string | null;
          sent_at?: string | null;
          opened_at?: string | null;
          started_at?: string | null;
          last_saved_at?: string | null;
          completed_at?: string | null;
          expires_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "form_submissions_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "form_submissions_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "form_submissions_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
          { foreignKeyName: "form_submissions_template_id_fkey"; columns: ["template_id"]; isOneToOne: false; referencedRelation: "form_templates"; referencedColumns: ["id"] },
        ];
      };
      form_templates: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          project_type: Database["public"]["Enums"]["project_type"] | null;
          is_archived: boolean;
          is_demo: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          public_token: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          project_type?: Database["public"]["Enums"]["project_type"] | null;
          is_archived?: boolean;
          is_demo?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          public_token?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          project_type?: Database["public"]["Enums"]["project_type"] | null;
          is_archived?: boolean;
          is_demo?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          public_token?: string | null;
        };
        Relationships: [
          { foreignKeyName: "form_templates_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      leads: {
        Row: {
          id: string;
          name: string;
          business_name: string | null;
          phone: string | null;
          phone_digits: string | null;
          email: string | null;
          source: Database["public"]["Enums"]["lead_source"];
          project_type: Database["public"]["Enums"]["project_type"] | null;
          estimated_value: number | null;
          status: Database["public"]["Enums"]["lead_status"];
          notes: string | null;
          follow_up_date: string | null;
          converted_client_id: string | null;
          converted_project_id: string | null;
          converted_at: string | null;
          is_demo: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          business_name?: string | null;
          phone?: string | null;
          phone_digits?: never;
          email?: string | null;
          source?: Database["public"]["Enums"]["lead_source"];
          project_type?: Database["public"]["Enums"]["project_type"] | null;
          estimated_value?: number | null;
          status?: Database["public"]["Enums"]["lead_status"];
          notes?: string | null;
          follow_up_date?: string | null;
          converted_client_id?: string | null;
          converted_project_id?: string | null;
          converted_at?: string | null;
          is_demo?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          business_name?: string | null;
          phone?: string | null;
          phone_digits?: never;
          email?: string | null;
          source?: Database["public"]["Enums"]["lead_source"];
          project_type?: Database["public"]["Enums"]["project_type"] | null;
          estimated_value?: number | null;
          status?: Database["public"]["Enums"]["lead_status"];
          notes?: string | null;
          follow_up_date?: string | null;
          converted_client_id?: string | null;
          converted_project_id?: string | null;
          converted_at?: string | null;
          is_demo?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "leads_converted_client_id_fkey"; columns: ["converted_client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "leads_converted_project_fk"; columns: ["converted_project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
          { foreignKeyName: "leads_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      notes: {
        Row: {
          id: string;
          client_id: string;
          project_id: string | null;
          body: string;
          is_pinned: boolean;
          author_id: string | null;
          created_at: string;
          updated_at: string;
          share_with_ai: boolean;
        };
        Insert: {
          id?: string;
          client_id: string;
          project_id?: string | null;
          body: string;
          is_pinned?: boolean;
          author_id?: string | null;
          created_at?: string;
          updated_at?: string;
          share_with_ai?: boolean;
        };
        Update: {
          id?: string;
          client_id?: string;
          project_id?: string | null;
          body?: string;
          is_pinned?: boolean;
          author_id?: string | null;
          created_at?: string;
          updated_at?: string;
          share_with_ai?: boolean;
        };
        Relationships: [
          { foreignKeyName: "notes_author_id_fkey"; columns: ["author_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "notes_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "notes_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
        ];
      };
      payments: {
        Row: {
          id: string;
          project_id: string;
          amount: number;
          paid_at: string;
          method: Database["public"]["Enums"]["payment_method"];
          kind: Database["public"]["Enums"]["payment_kind"];
          reference: string | null;
          note: string | null;
          external_provider: string | null;
          external_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          amount: number;
          paid_at?: string;
          method?: Database["public"]["Enums"]["payment_method"];
          kind?: Database["public"]["Enums"]["payment_kind"];
          reference?: string | null;
          note?: string | null;
          external_provider?: string | null;
          external_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          amount?: number;
          paid_at?: string;
          method?: Database["public"]["Enums"]["payment_method"];
          kind?: Database["public"]["Enums"]["payment_kind"];
          reference?: string | null;
          note?: string | null;
          external_provider?: string | null;
          external_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "payments_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "payments_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
        ];
      };
      portfolio_items: {
        Row: {
          id: string;
          project_id: string | null;
          client_id: string | null;
          title: string;
          category: string | null;
          summary: string | null;
          work_done: string | null;
          technologies: string[];
          site_url: string | null;
          status: string;
          position: number;
          published_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id?: string | null;
          client_id?: string | null;
          title: string;
          category?: string | null;
          summary?: string | null;
          work_done?: string | null;
          technologies?: string[];
          site_url?: string | null;
          status?: string;
          position?: number;
          published_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string | null;
          client_id?: string | null;
          title?: string;
          category?: string | null;
          summary?: string | null;
          work_done?: string | null;
          technologies?: string[];
          site_url?: string | null;
          status?: string;
          position?: number;
          published_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "portfolio_items_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "portfolio_items_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "portfolio_items_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
        ];
      };
      portfolio_media: {
        Row: {
          id: string;
          item_id: string;
          file_id: string;
          kind: string;
          position: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          item_id: string;
          file_id: string;
          kind?: string;
          position?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          item_id?: string;
          file_id?: string;
          kind?: string;
          position?: number;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "portfolio_media_file_id_fkey"; columns: ["file_id"]; isOneToOne: false; referencedRelation: "files"; referencedColumns: ["id"] },
          { foreignKeyName: "portfolio_media_item_id_fkey"; columns: ["item_id"]; isOneToOne: false; referencedRelation: "portfolio_items"; referencedColumns: ["id"] },
        ];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: Database["public"]["Enums"]["staff_role"];
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string;
          role?: Database["public"]["Enums"]["staff_role"];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: Database["public"]["Enums"]["staff_role"];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      project_ai_handoff_files: {
        Row: {
          id: string;
          handoff_id: string;
          name: string;
          content: string;
          position: number;
        };
        Insert: {
          id?: string;
          handoff_id: string;
          name: string;
          content: string;
          position?: number;
        };
        Update: {
          id?: string;
          handoff_id?: string;
          name?: string;
          content?: string;
          position?: number;
        };
        Relationships: [
          { foreignKeyName: "project_ai_handoff_files_handoff_id_fkey"; columns: ["handoff_id"]; isOneToOne: false; referencedRelation: "project_ai_handoffs"; referencedColumns: ["id"] },
        ];
      };
      project_ai_handoffs: {
        Row: {
          id: string;
          project_id: string;
          options: Json;
          mega_prompt: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          options?: Json;
          mega_prompt: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          options?: Json;
          mega_prompt?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "project_ai_handoffs_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "project_ai_handoffs_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
        ];
      };
      project_approvals: {
        Row: {
          id: string;
          project_id: string;
          title: string;
          description: string | null;
          kind: string;
          preview_url: string | null;
          file_ids: string[];
          status: string;
          create_task_on_changes: boolean;
          change_task_id: string | null;
          responded_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          title: string;
          description?: string | null;
          kind?: string;
          preview_url?: string | null;
          file_ids?: string[];
          status?: string;
          create_task_on_changes?: boolean;
          change_task_id?: string | null;
          responded_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          title?: string;
          description?: string | null;
          kind?: string;
          preview_url?: string | null;
          file_ids?: string[];
          status?: string;
          create_task_on_changes?: boolean;
          change_task_id?: string | null;
          responded_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "project_approvals_change_task_id_fkey"; columns: ["change_task_id"]; isOneToOne: false; referencedRelation: "tasks"; referencedColumns: ["id"] },
          { foreignKeyName: "project_approvals_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "project_approvals_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
        ];
      };
      project_links: {
        Row: {
          id: string;
          project_id: string;
          kind: string;
          label: string | null;
          url: string;
          note: string | null;
          client_visible: boolean;
          position: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          kind?: string;
          label?: string | null;
          url: string;
          note?: string | null;
          client_visible?: boolean;
          position?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          kind?: string;
          label?: string | null;
          url?: string;
          note?: string | null;
          client_visible?: boolean;
          position?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "project_links_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "project_links_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
        ];
      };
      project_references: {
        Row: {
          id: string;
          project_id: string;
          title: string;
          url: string;
          category: string;
          note: string | null;
          position: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          title: string;
          url: string;
          category?: string;
          note?: string | null;
          position?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          title?: string;
          url?: string;
          category?: string;
          note?: string | null;
          position?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "project_references_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "project_references_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
        ];
      };
      projects: {
        Row: {
          id: string;
          client_id: string;
          name: string;
          project_type: Database["public"]["Enums"]["project_type"];
          description: string | null;
          total_price: number;
          deposit_amount: number;
          status: Database["public"]["Enums"]["project_status"];
          status_changed_at: string;
          board_position: number;
          start_date: string | null;
          deadline: string | null;
          next_action: string | null;
          notes: string | null;
          completed_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          tech_stack: string | null;
          client_update: string | null;
          client_action: string | null;
          portal_token: string | null;
          portal_enabled_at: string | null;
        };
        Insert: {
          id?: string;
          client_id: string;
          name: string;
          project_type?: Database["public"]["Enums"]["project_type"];
          description?: string | null;
          total_price?: number;
          deposit_amount?: number;
          status?: Database["public"]["Enums"]["project_status"];
          status_changed_at?: string;
          board_position?: number;
          start_date?: string | null;
          deadline?: string | null;
          next_action?: string | null;
          notes?: string | null;
          completed_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          tech_stack?: string | null;
          client_update?: string | null;
          client_action?: string | null;
          portal_token?: string | null;
          portal_enabled_at?: string | null;
        };
        Update: {
          id?: string;
          client_id?: string;
          name?: string;
          project_type?: Database["public"]["Enums"]["project_type"];
          description?: string | null;
          total_price?: number;
          deposit_amount?: number;
          status?: Database["public"]["Enums"]["project_status"];
          status_changed_at?: string;
          board_position?: number;
          start_date?: string | null;
          deadline?: string | null;
          next_action?: string | null;
          notes?: string | null;
          completed_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          tech_stack?: string | null;
          client_update?: string | null;
          client_action?: string | null;
          portal_token?: string | null;
          portal_enabled_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "projects_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "projects_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      social_albums: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          client_id: string | null;
          project_id: string | null;
          status: Database["public"]["Enums"]["social_album_status"];
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          client_id?: string | null;
          project_id?: string | null;
          status?: Database["public"]["Enums"]["social_album_status"];
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          client_id?: string | null;
          project_id?: string | null;
          status?: Database["public"]["Enums"]["social_album_status"];
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "social_albums_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "social_albums_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "social_albums_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
        ];
      };
      task_checklist_items: {
        Row: {
          id: string;
          task_id: string;
          title: string;
          is_done: boolean;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          task_id: string;
          title: string;
          is_done?: boolean;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          task_id?: string;
          title?: string;
          is_done?: boolean;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "task_checklist_items_task_id_fkey"; columns: ["task_id"]; isOneToOne: false; referencedRelation: "tasks"; referencedColumns: ["id"] },
        ];
      };
      tasks: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          client_id: string | null;
          project_id: string | null;
          due_date: string | null;
          priority: Database["public"]["Enums"]["task_priority"];
          status: Database["public"]["Enums"]["task_status"];
          completed_at: string | null;
          position: number;
          assigned_to: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          start_date: string | null;
          blocked_by_task_id: string | null;
          internal_notes: string | null;
          links: Json;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          client_id?: string | null;
          project_id?: string | null;
          due_date?: string | null;
          priority?: Database["public"]["Enums"]["task_priority"];
          status?: Database["public"]["Enums"]["task_status"];
          completed_at?: string | null;
          position?: number;
          assigned_to?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          start_date?: string | null;
          blocked_by_task_id?: string | null;
          internal_notes?: string | null;
          links?: Json;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          client_id?: string | null;
          project_id?: string | null;
          due_date?: string | null;
          priority?: Database["public"]["Enums"]["task_priority"];
          status?: Database["public"]["Enums"]["task_status"];
          completed_at?: string | null;
          position?: number;
          assigned_to?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          start_date?: string | null;
          blocked_by_task_id?: string | null;
          internal_notes?: string | null;
          links?: Json;
        };
        Relationships: [
          { foreignKeyName: "tasks_assigned_to_fkey"; columns: ["assigned_to"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "tasks_blocked_by_task_id_fkey"; columns: ["blocked_by_task_id"]; isOneToOne: false; referencedRelation: "tasks"; referencedColumns: ["id"] },
          { foreignKeyName: "tasks_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "tasks_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "tasks_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
        ];
      };
      workspace_settings: {
        Row: {
          id: boolean;
          business_name: string;
          contact_email: string | null;
          contact_phone: string | null;
          form_intro: string;
          created_at: string;
          updated_at: string;
          legal_name: string | null;
          business_id: string | null;
          address: string | null;
          signatory_name: string | null;
        };
        Insert: {
          id?: boolean;
          business_name?: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          form_intro?: string;
          created_at?: string;
          updated_at?: string;
          legal_name?: string | null;
          business_id?: string | null;
          address?: string | null;
          signatory_name?: string | null;
        };
        Update: {
          id?: boolean;
          business_name?: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          form_intro?: string;
          created_at?: string;
          updated_at?: string;
          legal_name?: string | null;
          business_id?: string | null;
          address?: string | null;
          signatory_name?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      client_financials: {
        Row: {
          client_id: string;
          total_price: number;
          amount_paid: number;
          balance_due: number;
          project_count: number;
        };
        Relationships: [];
      };
      project_financials: {
        Row: {
          project_id: string;
          client_id: string;
          total_price: number;
          deposit_amount: number;
          amount_paid: number;
          balance_due: number;
          deposit_covered: boolean;
          last_payment_at: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      convert_lead: { Args: { p_lead_id: string; p_create_project?: boolean; p_project_name?: string }; Returns: Json };
      dashboard_metrics: { Args: Record<PropertyKey, never>; Returns: Json };
      duplicate_form_template: { Args: { p_template_id: string; p_name?: string }; Returns: string };
      finalize_questionnaire: { Args: { p_submission_id: string; p_answers: Json; p_client: Json }; Returns: Json };
      format_ils: { Args: { amount: number }; Returns: string };
      is_owner: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_staff: { Args: Record<PropertyKey, never>; Returns: boolean };
      project_status_label: { Args: { s: Database["public"]["Enums"]["project_status"] }; Returns: string };
      project_type_label: { Args: { t: Database["public"]["Enums"]["project_type"] }; Returns: string };
      reorder_form_questions: { Args: { p_section_id: string; p_ids: string[] }; Returns: undefined };
      reorder_form_sections: { Args: { p_template_id: string; p_ids: string[] }; Returns: undefined };
      respond_to_approval: { Args: { p_token: string; p_approval_id: string; p_decision: string; p_comment?: string; p_author?: string }; Returns: Json };
      task_status_label: { Args: { s: Database["public"]["Enums"]["task_status"] }; Returns: string };
    };
    Enums: {
      client_status: "active" | "maintenance" | "on_hold" | "completed" | "archived";
      contract_status: "draft" | "sent" | "signed" | "cancelled";
      file_category: "branding" | "references" | "site_texts" | "images" | "contracts" | "questionnaire" | "invoices" | "client_materials" | "deliverables" | "social" | "other";
      lead_source: "website" | "referral" | "instagram" | "facebook" | "google" | "whatsapp" | "returning_client" | "other";
      lead_status: "new" | "contacted" | "qualified" | "proposal_sent" | "converted" | "lost";
      payment_kind: "deposit" | "installment" | "final" | "other";
      payment_method: "bank_transfer" | "bit" | "cash" | "credit_card" | "other";
      project_status: "lead" | "questionnaire_sent" | "questionnaire_received" | "awaiting_deposit" | "design" | "development" | "testing" | "awaiting_approval" | "awaiting_final_payment" | "completed";
      project_type: "business_site" | "landing_page" | "ecommerce" | "web_app" | "other";
      question_type: "short_text" | "long_text" | "email" | "phone" | "yes_no" | "single_select" | "multi_select" | "number" | "url" | "date" | "color" | "image_upload" | "file_upload" | "reference_links";
      social_album_status: "collecting" | "editing" | "published";
      staff_role: "owner" | "admin" | "member";
      submission_status: "created" | "sent" | "in_progress" | "completed" | "cancelled";
      task_priority: "low" | "medium" | "high" | "urgent";
      task_status: "todo" | "in_progress" | "waiting_client" | "blocked" | "done";
    };
    CompositeTypes: Record<string, never>;
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type Views<T extends keyof PublicSchema["Views"]> = PublicSchema["Views"][T]["Row"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];
